MyQueue<int> intQueue = new MyQueue<int>();
intQueue.Enqueue(1);
intQueue.Enqueue(2);
intQueue.Enqueue(3);
intQueue.Enqueue(4);
Console.WriteLine("INT LIST HERE BEFORE DEQUEUE");
intQueue.PrintEls();
intQueue.Dequeue();
Console.WriteLine("INT LIST HERE AFTER DEQUEUE");
intQueue.PrintEls();
Console.WriteLine(intQueue.Contains(2));
Console.WriteLine(intQueue.Contains(555));
Console.WriteLine("Count -> " + intQueue.Count);
Console.WriteLine("INT STACK HERE AFTER CLEAR");
intQueue.Clear();
intQueue.PrintEls();
Console.WriteLine("------------------------");

MyQueue<string> stringQueue = new MyQueue<string>();
stringQueue.Enqueue("str1");
stringQueue.Enqueue("str2");
stringQueue.Enqueue("str3");
stringQueue.Enqueue("str4");
Console.WriteLine("STRING LIST HERE BEFORE DEQUEUE");
stringQueue.PrintEls();
stringQueue.Dequeue();
Console.WriteLine("STRING LIST HERE AFTER DEQUEUE");
stringQueue.PrintEls();
Console.WriteLine(stringQueue.Contains("str2"));
Console.WriteLine(stringQueue.Contains("str888"));
Console.WriteLine("Count -> " + stringQueue.Count);
Console.WriteLine("STRING STACK HERE AFTER CLEAR");
stringQueue.Clear();
stringQueue.PrintEls();
Console.WriteLine("------------------------");