MyStack<int> intStack = new MyStack<int>();
intStack.Push(1);
intStack.Push(2);
intStack.Push(3);
intStack.Push(4);
Console.WriteLine("INT STACK HERE BEFORE POP");
intStack.PrintEls();
intStack.Pop();
Console.WriteLine("INT STACK HERE AFTER POP");
intStack.PrintEls();
Console.WriteLine(intStack.Contains(2));
Console.WriteLine(intStack.Contains(555));
Console.WriteLine("Count -> " + intStack.Count);
Console.WriteLine("INT STACK HERE AFTER CLEAR");
intStack.Clear();
intStack.PrintEls();
Console.WriteLine("------------------------");

MyStack<string> stringStack = new MyStack<string>();
stringStack.Push("str1");
stringStack.Push("str2");
stringStack.Push("str3");
stringStack.Push("str4");
Console.WriteLine("STRING STACK HERE BEFORE POP");
stringStack.PrintEls();
stringStack.Pop();
Console.WriteLine("STRING STACK HERE AFTER POP");
stringStack.PrintEls();
Console.WriteLine(stringStack.Contains("str2"));
Console.WriteLine(stringStack.Contains("str888"));
Console.WriteLine("Count -> " + stringStack.Count);
Console.WriteLine("STRING STACK HERE AFTER CLEAR");
stringStack.Clear();
stringStack.PrintEls();
Console.WriteLine("------------------------");