MyList<int> intList = new MyList<int>();
intList.Add(1);
intList.Add(2);
intList.Add(3);
intList.Add(4);
Console.WriteLine("INT LIST HERE BEFORE REMOVE");
intList.PrintEls();
Console.WriteLine("INT LIST HERE AFTER REMOVE");
intList.Remove();
intList.PrintEls();
Console.WriteLine("INT LIST HERE AFTER REMOVE AT");
intList.RemoveAt(0);
intList.PrintEls();
Console.WriteLine(intList.Contains(2));
Console.WriteLine(intList.Contains(555));
Console.WriteLine("Count -> " + intList.Count);
Console.WriteLine("INT STACK HERE AFTER CLEAR");
intList.Clear();
intList.PrintEls();
Console.WriteLine("------------------------");

MyList<string> stringList = new MyList<string>();
stringList.Add("str1");
stringList.Add("str2");
stringList.Add("str3");
stringList.Add("str4");
Console.WriteLine("STRING LIST HERE BEFORE REMOVE");
stringList.PrintEls();
Console.WriteLine("STRING LIST HERE AFTER REMOVE");
stringList.Remove();
stringList.PrintEls();
Console.WriteLine("STRING LIST HERE AFTER REMOVE AT");
stringList.RemoveAt(0);
stringList.PrintEls();
Console.WriteLine(stringList.Contains("str2"));
Console.WriteLine(stringList.Contains("str888"));
Console.WriteLine("Count -> " + stringList.Count);
Console.WriteLine("STRING STACK HERE AFTER CLEAR");
stringList.Clear();
stringList.PrintEls();
Console.WriteLine("------------------------");